### ISSUE TITLE
Brain Board Review

### ISSUE THREAD

**Issue by ToniCorinne** [AndyEngland521/Light_Suit#2]
# Schematic
- [x] Fix your labels on DATINT(pin 23) and R16 to make it easier to read - future you will appreciate it
## Microphone
- [x] Assuming the note for the through hole resistor is meant for R6? label that to make it clearer. Or if the gain is meant to be customized on the application, clarify that you're using a 1K here, but the general formula is what you have posted. 
- [x] R7 is 1K, but your note says it should be 2K. Did you want 1A I_CHG value? Either fix your note or fix your resistor. 

# Board 
- [x] Add your name to the "designed by:" section
- [x] What's the reason for the cutout on the board by J1? Seems like you're adding unnecessary difficulty to you routing for your 3.3V line there.
- [x] That 3.3V line is awfully close to H1 and H2 - if you can move it away from where it could accidentally get snipped by a screw being over tightened, that'd be good
- [x] Same 3.3V line is awfully close to the bottom board edge - you could move in that in half a grid space for a bit more clearance
- [x] Those JST connectors can also be a PITA - do you want standard header holes connected on your JST lines in case you need to solder a diff connector on for repairs? 
- [x] Label your switches. Otherwise Tiny Dancer could push the wrong button at the wrong time
- [x] You've got an acid trap coming off of D3/Pad 14 on your ESP32. bump out that trace a bit coming off the pad
- [x] You could bump up your 5V trace width coming off of all of your LEDs. You've got the board space. You could really bump up all the traces coming off of those LEDs. 
- [x] Got a trace coming in to the corner of the pad on your C4 10nF cap - you could enter the pad straighter from either side
- [x] Same angle trace entry on C8 4.7uF cap
- [x] General design question - how come you're doing this as a single sided-design? You could consolidate the size down a bit by moving some components to the back (and probably minimize some of the distance on traces between LEDs)
- [x] Do you want a bit of overhang on your USB connector to give yourself freedom of USB cable to use?

**Comment by AndyEngland521** [comment]
- The reason for the cutout is so the wires for the battery can fit between the walls of the 3D printed case and the PCB

- Great idea on the headers for the JST

- The whole thing will be in a 3D printed belt buckle type scenario so right button will be up, left is down, then different functions are decided by single, double, press and hold etc. to change modes, gradients, and audio sensitivity. I might label it on the printed enclosure but I'm unsure

- I love entering pads from the corner

- To answer your design question, I prefer everything on the same side as then I can just paste it and put the paste away. Also, my battery is 75x50mm so the case needs to be this large anyway

- Good catch on the overhang for the USB!
